---
# [required]
remote_write_configuration:
  # [required] V2 URL endpoint of the Prometheus instance to be used by the data planes
  # to send metrics. The Prometheus instance has to offer a Remote Write endpoint.
  # If oidc_configuration is set that endpoint has to be offered under the
  # /api/v1/metrics/<tenant>/api/v1/receive" URL path, where <tenant> is defined by the
  # --observability-red-hat-sso-tenant Fleet Manager flag.
  # If oidc_coniguration is set that endpoint has to be offered under the
  # "/" URL path.
  # The format of remote_write_url is `<url-scheme>:<hostname>:<port>` where
  # <port> is optional.
  remote_write_url: https://observability-rw-proxy-managed-services-stage.apps.app-sre-stage-0.k3s7.p1.openshiftapps.com
